# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
            entity:
                class: ItraBundle:User
                property: username

    encoders:
        ItraBundle\Entity\User:
            algorithm: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: our_db_provider

            form_login:
                login_path: /login
                check_path: /login

            logout:
                path:   /logout
                target: /login
            anonymous: ~

    role_hierarchy:
            ROLE_MODERATOR:       ROLE_USER
            ROLE_ADMIN: [ROLE_MODERATOR, ROLE_USER]

    access_control:
            - { path: ^/login, allow_if: "not has_role('ROLE_USER')" }
            - { path: ^/register, allow_if: "not has_role('ROLE_USER')" }
            - { path: ^/reset_pass, allow_if: "not has_role('ROLE_USER')" }
            - { path: ^/input_new_password, allow_if: "not has_role('ROLE_USER')" }
            - { path: ^/catalog, roles: ROLE_USER }
            - { path: ^/category/ajax, roles: ROLE_USER }
            - { path: ^/product, roles: ROLE_MODERATOR }
            - { path: ^/category, roles: ROLE_MODERATOR }
            - { path: ^/user, roles: ROLE_MODERATOR }




            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
