# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.images_uploader:
        class: ItraBundle\Services\ImageUploader
        arguments: ['%images_directory%']

    app.menu_builder:
        class: ItraBundle\Services\MenuBuilder
        arguments: ["@knp_menu.factory", "@doctrine.orm.entity_manager"]
        tags:
            - { name: knp_menu.menu_builder, method: createAdminMenu, alias: admin }
            - { name: knp_menu.menu_builder, method: createModeratorMenu, alias: moderator }
            - { name: knp_menu.menu_builder, method: createUserMenu, alias: user }
            - { name: knp_menu.menu_builder, method: createGuestMenu, alias: guest }

    app.product_serialize:
        class: ItraBundle\Services\ProductSerializer

    app.my_serialize:
        class: ItraBundle\Services\MySerializer

    #app.exception_listener:
    #    class: ItraBundle\Services\RedirectUserListener
    #    arguments:
    #                - "@router"
    #    tags:
    #        - { name: kernel.event_listener, event: kernel.exception }

    pagination:
        class: ItraBundle\Services\Pagination
        arguments: [ "@doctrine.orm.entity_manager" ]